language: java

matrix:
  include:
  - os: linux
    jdk: oraclejdk8

  - os: osx
    osx_image: xcode8.3 # see https://docs.travis-ci.com/user/osx-ci-environment/




install: false

script:
  - mvn  -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B

cache:
  directories:
  - $HOME/.m2
  - $HOME/.binaries

after_success:
- mvn clean